
>P1;testing
sequence::     : :     : :::-1.00:-1.00
LSAILNRVCLLHEKTPVSEHVTKCCSGSLVERRPCFSALTVDETYVPKEFKAETFTFHSDICTLPEKEKQIKKQT*

>P1;3V09
sequence::     : :     : :::-1.00:-1.00
LSVVLNRLCVLHEKTPVSEKVTKCCSESLVDRRPCFSALGPDETYVPKEFNAETFTFHADICTLPETERKIKKQT*
