
>P1;3V09
structureX:backend/atom_files/3V09.pdb:   1 :A:+583 :A:MOL_ID  1; MOLECULE  SERUM ALBUMIN; CHAIN  A:MOL_ID  1; ORGANISM_SCIENTIFIC  ORYCTOLAGUS CUNICULUS; ORGANISM_COMMON  EUROPEAN RABBIT,JAPANESE WHITE RABBIT,DOME RABBIT,RABBITS; ORGANISM_TAXID  9986: 2.27: 0.19
EAHKSEIAHRFNDVGEEHFIGLVLITFSQYLQKCPYEEHAKLVKEVTDLAKACVADESAANCDKSLHDIFGDKIC
ALPSLRDTYGDVADCCEKKEPERNECFLHHKDDKPDLPPFARPEADVLCKAFHDDEKAFFGHYLYEVARRHPYFY
APELLYYAQKYKAILTECCEAADKGACLTPKLDALEGKSLISAAQERLRCASIQKFGDRAYKAWALVRLSQRFPK
ADFTDISKIVTDLTKVHKECCHGDLLECADDRADLAKYMCEHQETISSHLKECCDKPILEKAHCIYGLHNDETPA
GLPAVAEEFVEDKDVCKNYEEAKDLFLGKFLYEYSRRHPDYSVVLLLRLGKAYEATLKKCCATDDPHACYAKVLD
EFQPLVDEPKNLVKQNCELYEQLGDYNFQNALLVRYTKKVPQVSTPTLVEISRSLGKVGSKCCKHPEAERLPCVE
DYLSVVLNRLCVLHEKTPVSEKVTKCCSESLVDRRPCFSALGPDETYVPKEFNAETFTFHADICTLPETERKIKK
QTALVELVKHKPHATNDQLKTVVGEFTALLDKCCSAEDKEACFAVEGPKLVESSKATL*

>P1;testing
sequence::     : :     : :::-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
--LSAILNRVCLLHEKTPVSEHVTKCCSGSLVERRPCFSALTVDETYVPKEFKAETFTFHSDICTLPEKEKQIKK
QT--------------------------------------------------------*
